---
title: "bw-exam2"
format: html
---

```{r}
library(tidytuesdayR)
library(tidyverse)
library(rnaturalearth)
library(sf)
```

```{r}
tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption
```

```{r}
fcc <- fc |>
  mutate(food_category = fct_recode(food_category, "Lamb & Goat" = "Lamb",
         "Milk - inc. cheese" = "Dairy",
         "Wheat and Wheat Products" = "Wheat",
         "Nuts inc, Peanut Butter" = "Nuts"))
```


```{r} 
fcc |>
  group_by(country) |>
  summarize(consumption = sum(consumption)) |>
  arrange(desc(consumption)) |>
  head(5) |>
  ggplot(aes(x = country, y = consumption, color = country)) +
  geom_boxplot()
```

```{r}
fcc |>
  group_by(food_category) |>
  slice_max(country) |>
  select(food_category, country, consumption) #|>
  #ggplot(aes(x = )) # ?
```

```{r}
# fcc |>
#   boundary() |>
#   # ?
```

```{r}
# ne_countries(returnclass = "sf") |>
#   select(name, geometry) |>
#   mutate(name = ifelse(name == "United States of America", "USA", name)) |>
#   mutate(name = ifelse(name == "Bosnia and Herz.", "Bosnia and Herzegovina", name)) |>
#   mutate(name = ifelse(name == "Czechia", "Czech Republic", name)) |>
#   mutate(name == "Taiwan", "Taiwan.ROC", name) |>
#   left_join(
#     fcc |>
#       select(-co2_emmission) |>
#       group_by(food_category) |>
#       mutate(consumption = (consumption - mean(consumption))/sd(consumption)), join_by(name == country)) |>
#   pivot_wider(names_from = food_category, values_from = consumption) |>
#   select(-"NA") |>
#   pivot_longer(cols = c(-name, -geometry), 
#                names_to = "food_category", 
#                values_to = "consumption") |> # Figure out issue here
#   ggplot() +
#   geom_sf(aes(fill = consumption)) +
#   facet_wrap(~food_category) +
#   theme(legend.position = "bottom")
```


