---
title: "ica-reshaping"
format: html
---

```{r}
library(tidyverse)
penguins <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv')
```
```{r}
penguin_avg <- penguins |> 
  group_by(species, sex) |> 
  summarize(avg_body_mass = mean(body_mass_g, na.rm = TRUE)) |> 
  na.omit()
```
```{r}
# Units of observation = ???
head(penguins)
```
```{r}
# Units of observation = ???
head(penguin_avg)
```
```{r}
penguin_avg |> 
pivot_wider(names_from = sex, values_from = avg_body_mass)
```
```{r}
penguin_avg_wide <- penguin_avg |> 
  pivot_wider(names_from = sex, values_from = avg_body_mass)

penguin_avg_wide
```
```{r}
# We can either communicate which variables we WANT to collect into a single column (female, male)
penguin_avg_wide |> 
  pivot_longer(cols = c(female, male), names_to = "sex", values_to = "avg_body_mass")
```
```{r}
# Or which variable(s) we do NOT want to collect into a single column (sex)
penguin_avg_wide |> 
  pivot_longer(cols = -species, names_to = "sex", values_to = "avg_body_mass")
```
```{r}
food <- data.frame(
  customer = rep(c("A", "B"), each = 3),
  restaurant = rep(c("Shish", "FrenchMeadow", "DunnBros"), 2),
  order = c("falafel", "salad", "coffee", "baklava", "pastry", "tea")
)
food
food |>
  pivot_wider(names_from = restaurant, values_from = order)
```
```{r}
more_food <- data.frame(
  customer = c("C", "D"),
  Shish = c("coffee", "maza"),
  FrenchMeadow = c("soup", "sandwich"),
  DunnBros = c("cookie", "coffee")
)
more_food

more_food |>
  pivot_longer(cols = c(Shish, FrenchMeadow, DunnBros), names_to = "restaurant", values_to = "order")
```
```{r}
sleep_wide <- read.csv("https://mac-stat.github.io/data/sleep_wide.csv")

head(sleep_wide) #What are the units of observation
```
```{r}
sleep_wide |>
  pivot_longer(cols = 2:11, names_to = "day_restriction", values_to = "reaction_time", names_prefix = "day_")
```
```{r}
sleep_long <- sleep_wide |>
  pivot_longer(cols = -Subject, #Every subject except one that is getting "-"
               names_to = "day",
               names_prefix = "day_",
               values_to = "reaction_time")

head(sleep_long)
# Make a line plot
```
```{r}
sleep_long <- sleep_wide |>
  pivot_longer(cols = -Subject,
               names_to = "day",
               names_prefix = "day_",
               values_to = "reaction_time") |> 
  mutate(Subject = as.factor(Subject), day = as.numeric(day))

# Check it out
# Same data, different class
head(sleep_long)
```

